import type { Translate } from "./i18n";
import { TIMELINE_LABELS } from "./timelineLabels";

// Presentation labels for codes the API returns (roles, permission keys,
// audit actions, entity types). Codes themselves stay unchanged in API data;
// an unknown code (e.g. a custom role) is shown as-is.
type Labels = Readonly<Record<string, readonly [string, string]>>;

export const labelOf = (map: Labels, code: string, t: Translate) => {
  const hit = map[code];
  return hit ? t(hit[0], hit[1]) : code;
};

export const ROLE_LABELS: Labels = {
  SUPER_ADMIN: ["مدير النظام", "System administrator"],
  CENTER_DIRECTOR: ["مدير المركز", "Center director"],
  MEDICAL_DIRECTOR: ["المدير الطبي", "Medical director"],
  DOCTOR: ["طبيب", "Doctor"],
  HEAD_NURSE: ["رئيس التمريض", "Head nurse"],
  NURSE: ["ممرض", "Nurse"],
  PHARMACIST: ["صيدلي", "Pharmacist"],
  WAREHOUSE: ["أمين المستودع", "Warehouse"],
  LAB_TECHNICIAN: ["فني مختبر", "Lab technician"],
  RECEPTION: ["الاستقبال", "Reception"],
  MAINTENANCE: ["الصيانة", "Maintenance"],
  ACCOUNTANT: ["محاسب", "Accountant"],
  AUDITOR: ["مدقق", "Auditor"],
};

export const PERMISSION_LABELS: Labels = {
  "user.view": ["عرض حسابات المستخدمين", "View user accounts"],
  "user.create": ["إنشاء حسابات المستخدمين", "Create user accounts"],
  "user.edit": ["تعديل حسابات المستخدمين", "Edit user accounts"],
  "user.deactivate": ["تعطيل حسابات المستخدمين", "Deactivate user accounts"],
  "role.manage": ["إدارة الأدوار", "Manage roles"],
  "permission.manage": ["إدارة صلاحيات الأدوار", "Manage role permissions"],
  "audit.view": ["عرض سجل التدقيق", "View audit log"],
  "patient.view": ["عرض ملفات المرضى", "View patient records"],
  "patient.create": ["تسجيل مرضى جدد", "Register new patients"],
  "patient.edit": ["تعديل ملفات المرضى", "Edit patient records"],
  "patient.alert.manage": ["إدارة التنبيهات السريرية", "Manage clinical alerts"],
  "scheduling.manage": ["إدارة خطط الديلزة والجدول اليومي", "Manage dialysis plans and schedule"],
  "dialysis.emergency.create": ["إنشاء جلسات ديلزة طارئة", "Create emergency sessions"],
  "shift.manage": ["تعديل سعة الورديات", "Edit shift capacity"],
  "attendance.checkin": ["تسجيل حضور المرضى", "Check patients in"],
  "inventory.view": ["عرض المخزون", "View inventory"],
  "inventory.manage": ["إدارة المخزون وملفات المستلزمات", "Manage inventory and supply profiles"],
  "inventory.issue": ["صرف مستلزمات الجلسات", "Issue session supplies"],
  "machine.view": ["عرض الأقسام والأجهزة", "View wards and machines"],
  "machine.manage": ["إدارة الأقسام والأجهزة", "Manage wards and machines"],
  "machine.assign": ["إسناد الأجهزة للجلسات", "Assign machines to sessions"],
  "approval.machine.decide": ["الموافقة على استخدام الأجهزة المحمية", "Approve protected machine use"],
  "dialysis.session.view": ["عرض جلسات الديلزة", "View dialysis sessions"],
  "dialysis.pre.record": ["تسجيل تقييم ما قبل الديلزة", "Record pre-dialysis assessment"],
  "dialysis.start": ["بدء جلسة الديلزة", "Start dialysis session"],
  "dialysis.reading.create": ["تسجيل قراءات الجلسة", "Record session readings"],
  "dialysis.event.create": ["تسجيل أحداث الجلسة", "Record session events"],
  "dialysis.end": ["إنهاء الجلسة وتسجيل الخروج", "End session and discharge"],
  "nursing.assign": ["توزيع الممرضين على المرضى", "Assign nurses to patients"],
  "nursing.ward.view": ["عرض لوحة القسم (المرضى المسندون)", "View ward dashboard (assigned)"],
  "nursing.ward.view.all": ["عرض لوحة القسم كاملة", "View full ward dashboard"],
  "prescription.create": ["إنشاء أوامر الطبيب والملاحظات السريرية", "Create doctor orders and notes"],
  "prescription.modify": ["إيقاف أو تعديل أوامر الطبيب", "Stop or modify doctor orders"],
  "medication.administer": ["تسجيل إعطاء الدواء", "Record medication given"],
  "lab.catalog.manage": ["إدارة قائمة التحاليل", "Manage lab catalog"],
  "lab.request": ["طلب تحاليل", "Order lab tests"],
  "lab.queue.view": ["عرض قائمة طلبات المختبر", "View lab queue"],
  "lab.result.create": ["إدخال وتعديل نتائج المختبر", "Enter and amend lab results"],
  "pharmacy.dispense": ["صرف الوصفات", "Dispense prescriptions"],
  "inventory.batch.manage": ["إدارة الدفعات وتواريخ الانتهاء", "Manage batches and expiry"],
  "inventory.transfer.request": ["طلب تحويل مخزون", "Request stock transfer"],
  "inventory.transfer.approve": ["اعتماد تحويل المخزون", "Approve stock transfer"],
  "inventory.transfer.issue": ["إصدار تحويل المخزون", "Issue stock transfer"],
  "inventory.transfer.receive": ["استلام تحويل المخزون", "Receive stock transfer"],
  "machine.fault.report": ["الإبلاغ عن عطل جهاز", "Report machine fault"],
  "maintenance.manage": ["إدارة تذاكر الصيانة", "Manage maintenance tickets"],
  "incident.report": ["الإبلاغ عن حادثة", "Report incident"],
  "incident.view": ["عرض الحوادث", "View incidents"],
  "incident.review": ["مراجعة وإغلاق الحوادث", "Review and close incidents"],
  "quality.audit.view": ["عرض التدقيق السريري", "View clinical audit"],
  "user.reset_password": ["إعادة تعيين كلمة المرور أو PIN", "Reset password or PIN"],
  "audit.export": ["تصدير سجل التدقيق", "Export audit trail"],
  "entry.create": ["كتابة التقارير والملاحظات", "Write staff entries"],
  "entry.review": ["مراجعة تقارير الموظفين", "Review staff entries"],
  "settings.manage": ["تعديل إعدادات النظام", "Change system settings"],
  "oversight.view": ["لوحة الرقابة", "Oversight dashboard"],
  "task.create": ["إنشاء المهام وإسنادها", "Create and route tasks"],
  "task.manage": ["إدارة جميع المهام", "Manage all tasks"],
};

export const ENTITY_TYPE_LABELS: Labels = {
  AccessRecord: ["الوصول الوعائي", "Vascular access"],
  AuditLog: ["سجل التدقيق", "Audit log"],
  ClinicalAlert: ["تنبيه سريري", "Clinical alert"],
  DialysisReading: ["قراءة ديلزة", "Dialysis reading"],
  DialysisSchedule: ["موعد", "Appointment"],
  DialysisSession: ["جلسة ديلزة", "Dialysis session"],
  DoctorOrder: ["أمر طبيب", "Doctor order"],
  IncidentReport: ["بلاغ حادثة", "Incident report"],
  InventoryBatch: ["دفعة مخزون", "Inventory batch"],
  InventoryItem: ["صنف مخزون", "Inventory item"],
  LabOrder: ["طلب مختبر", "Lab order"],
  LabOrderItem: ["تحليل", "Lab test"],
  LabResult: ["نتيجة مختبر", "Lab result"],
  Machine: ["جهاز", "Machine"],
  MachineUsageApprovalRequest: ["طلب موافقة جهاز", "Machine approval request"],
  MaintenanceTicket: ["تذكرة صيانة", "Maintenance ticket"],
  MedicationAdministration: ["إعطاء دواء", "Medication given"],
  NursingAssignment: ["توزيع تمريض", "Nursing assignment"],
  Patient: ["مريض", "Patient"],
  Prescription: ["وصفة", "Prescription"],
  Role: ["دور", "Role"],
  SessionSupplyIssueItem: ["مستلزمات الجلسة", "Session supplies"],
  Shift: ["وردية", "Shift"],
  StaffEntry: ["تقرير موظف", "Staff entry"],
  StockTransfer: ["تحويل مخزون", "Stock transfer"],
  SystemSetting: ["إعداد النظام", "System setting"],
  Task: ["مهمة", "Task"],
  User: ["مستخدم", "User"],
  Ward: ["قسم", "Ward"],
};

export const AUDIT_ACTION_LABELS: Labels = {
  ACCESS_RECORD_CLOSED: ["إغلاق وصول وعائي", "Vascular access closed"],
  ACCESS_RECORD_CREATED: ["إضافة وصول وعائي", "Vascular access added"],
  ADD: ["إضافة", "Added"],
  AUDIT_EXPORTED: ["تصدير سجل التدقيق", "Audit exported"],
  CLINICAL_ALERT_ACKNOWLEDGED: ["الاطلاع على تنبيه سريري", "Clinical alert acknowledged"],
  CLINICAL_ALERT_CREATED: ["إضافة تنبيه سريري", "Clinical alert added"],
  CLINICAL_ALERT_RESOLVED: ["حل تنبيه سريري", "Clinical alert resolved"],
  DIALYSIS_DISCHARGED: ["خروج المريض", "Patient discharged"],
  DIALYSIS_ENDED: ["انتهاء الديلزة", "Dialysis ended"],
  DIALYSIS_INTERRUPTED: ["توقف الديلزة", "Dialysis interrupted"],
  DIALYSIS_MACHINE_REASSIGNED: ["تغيير جهاز الديلزة", "Dialysis machine reassigned"],
  DIALYSIS_PLAN_SET: ["تحديث خطة الديلزة", "Dialysis plan updated"],
  DIALYSIS_PRE_RECORDED: ["تسجيل تقييم ما قبل الديلزة", "Pre-dialysis recorded"],
  DIALYSIS_READING_AMENDED: ["تعديل قراءة", "Reading amended"],
  DIALYSIS_RESUMED: ["استئناف الديلزة", "Dialysis resumed"],
  DIALYSIS_STARTED: ["بدء الديلزة", "Dialysis started"],
  DIALYSIS_SUPPLIES_READY: ["تجهيز المستلزمات", "Supplies ready"],
  DOCTOR_ORDER_CREATED: ["إنشاء أمر طبيب", "Doctor order created"],
  DOCTOR_ORDER_MODIFIED: ["تعديل أمر طبيب", "Doctor order modified"],
  DOCTOR_ORDER_STOPPED: ["إيقاف أمر طبيب", "Doctor order stopped"],
  EMERGENCY_SESSION_CREATED: ["إنشاء جلسة طارئة", "Emergency session created"],
  EXTRA_SESSION_CREATED: ["إنشاء جلسة إضافية", "Extra session created"],
  INCIDENT_REPORTED: ["الإبلاغ عن حادثة", "Incident reported"],
  INCIDENT_STATUS_CHANGED: ["تغيير حالة حادثة", "Incident status changed"],
  INVENTORY_BATCH_RECEIVED: ["استلام دفعة مخزون", "Batch received"],
  INVENTORY_ITEM_CREATED: ["إضافة صنف مخزون", "Inventory item created"],
  LAB_ORDER_CREATED: ["إنشاء طلب مختبر", "Lab order created"],
  LAB_ORDER_ITEM_STATUS_CHANGED: ["تغيير حالة تحليل", "Lab test status changed"],
  LAB_RESULT_AMENDED: ["تصحيح نتيجة مختبر", "Lab result amended"],
  LAB_RESULT_ENTERED: ["إدخال نتيجة مختبر", "Lab result entered"],
  MACHINE_APPROVAL_EXPIRED: ["انتهاء طلب موافقة جهاز", "Machine approval expired"],
  MACHINE_APPROVAL_REQUESTED: ["طلب موافقة جهاز", "Machine approval requested"],
  MACHINE_ASSIGNED_AUTO: ["إسناد جهاز تلقائياً", "Machine auto-assigned"],
  MACHINE_ASSIGNED_MANUAL_OVERRIDE: ["إسناد جهاز يدوياً", "Machine assigned manually"],
  MACHINE_CREATED: ["إضافة جهاز", "Machine added"],
  MAINTENANCE_FAULT_REPORTED: ["الإبلاغ عن عطل", "Fault reported"],
  MAINTENANCE_TICKET_ASSIGNED: ["إسناد تذكرة صيانة", "Maintenance ticket assigned"],
  MAINTENANCE_TICKET_CANCELLED: ["إلغاء تذكرة صيانة", "Maintenance ticket cancelled"],
  MAINTENANCE_TICKET_CLOSED: ["إغلاق تذكرة صيانة", "Maintenance ticket closed"],
  MAINTENANCE_TICKET_STATUS_CHANGED: ["تغيير حالة تذكرة صيانة", "Maintenance ticket status changed"],
  MEDICATION_ADMINISTERED: ["إعطاء دواء", "Medication administered"],
  NURSING_ASSIGNMENT_SET: ["توزيع التمريض", "Nursing assignment set"],
  PATIENT_BREAK_GLASS_ACCESS: ["فتح ملف مريض طارئ", "Break-glass chart access"],
  PATIENT_CHECKED_IN: ["تسجيل حضور مريض", "Patient checked in"],
  PATIENT_CREATED: ["تسجيل مريض", "Patient registered"],
  PATIENT_DRY_WEIGHT_CHANGED: ["تغيير الوزن الجاف", "Dry weight changed"],
  PATIENT_MARKED_ABSENT: ["تسجيل غياب مريض", "Patient marked absent"],
  PATIENT_SUPPLY_PROFILE_ITEM_REMOVED: ["حذف مستلزم من ملف المريض", "Supply profile item removed"],
  PATIENT_SUPPLY_PROFILE_SET: ["تحديث مستلزمات المريض", "Supply profile set"],
  PATIENT_UPDATED: ["تحديث بيانات مريض", "Patient updated"],
  PATIENT_VIEWED: ["فتح ملف مريض", "Patient chart opened"],
  PRESCRIPTION_DISPENSED: ["صرف وصفة", "Prescription dispensed"],
  PRESCRIPTION_DISPENSING_STARTED: ["بدء صرف وصفة", "Dispensing started"],
  PRESCRIPTION_REJECTED_BY_PHARMACY: ["رفض الصيدلية لوصفة", "Rejected by pharmacy"],
  ROLE_CREATED: ["إنشاء دور", "Role created"],
  ROLE_DELETED: ["حذف دور", "Role deleted"],
  ROLE_PERMISSIONS_UPDATED: ["تحديث صلاحيات دور", "Role permissions updated"],
  SCHEDULE_RESCHEDULED: ["إعادة جدولة موعد", "Appointment rescheduled"],
  SESSION_SUPPLY_OVERRIDE_SET: ["تعديل مستلزمات الجلسة", "Session supplies overridden"],
  SESSION_SUPPLY_SUBSTITUTED: ["استبدال مستلزم", "Supply substituted"],
  SETTING_CHANGED: ["تغيير إعداد", "Setting changed"],
  SHIFT_CAPACITY_UPDATED: ["تحديث سعة الوردية", "Shift capacity updated"],
  STAFF_ENTRY_ASSIGNED: ["إسناد تقرير موظف", "Staff entry assigned"],
  STAFF_ENTRY_CREATED: ["كتابة تقرير موظف", "Staff entry created"],
  STAFF_ENTRY_ESCALATED: ["تصعيد تقرير موظف", "Staff entry escalated"],
  STAFF_ENTRY_STATUS_CHANGED: ["تغيير حالة تقرير", "Staff entry status changed"],
  STOCK_ADJUSTED: ["تعديل المخزون", "Stock adjusted"],
  STOCK_TRANSFERRED_TO_PHARMACY: ["تحويل مخزون للصيدلية", "Stock sent to pharmacy"],
  STOCK_TRANSFER_APPROVED: ["اعتماد تحويل مخزون", "Transfer approved"],
  STOCK_TRANSFER_CANCELLED: ["إلغاء تحويل مخزون", "Transfer cancelled"],
  STOCK_TRANSFER_ISSUED: ["إصدار تحويل مخزون", "Transfer issued"],
  STOCK_TRANSFER_RECEIVED: ["استلام تحويل مخزون", "Transfer received"],
  STOCK_TRANSFER_REJECTED: ["رفض تحويل مخزون", "Transfer rejected"],
  STOCK_TRANSFER_REQUESTED: ["طلب تحويل مخزون", "Transfer requested"],
  TASK_CREATED: ["إنشاء مهمة", "Task created"],
  TASK_STATUS_CHANGED: ["تغيير حالة مهمة", "Task status changed"],
  USER_ACTIVATED: ["تفعيل مستخدم", "User activated"],
  USER_CREATED: ["إنشاء مستخدم", "User created"],
  USER_DEACTIVATED: ["تعطيل مستخدم", "User deactivated"],
  USER_PASSWORD_RESET: ["إعادة تعيين كلمة المرور", "Password reset"],
  USER_PIN_RESET: ["تصفير PIN", "PIN reset"],
  USER_ROLES_CHANGED: ["تغيير أدوار مستخدم", "User roles changed"],
  USER_UPDATED: ["تحديث مستخدم", "User updated"],
  WARD_CREATED: ["إضافة قسم", "Ward added"],
};

// Permission groups (packages/shared PERMISSIONS module) and timeline source
// modules share one map.
export const MODULE_LABELS: Labels = {
  attendance: ["الحضور", "Attendance"],
  audit: ["التدقيق", "Audit"],
  dialysis: ["الديلزة", "Dialysis"],
  doctor: ["الطبيب", "Doctor"],
  "doctor-orders": ["أوامر الطبيب", "Doctor orders"],
  entries: ["تقارير الموظفين", "Staff entries"],
  inventory: ["المخزون", "Inventory"],
  lab: ["المختبر", "Lab"],
  laboratory: ["المختبر", "Lab"],
  machines: ["الأجهزة", "Machines"],
  maintenance: ["الصيانة", "Maintenance"],
  nursing: ["التمريض", "Nursing"],
  oversight: ["الرقابة", "Oversight"],
  patients: ["المرضى", "Patients"],
  pharmacy: ["الصيدلية", "Pharmacy"],
  quality: ["الجودة", "Quality"],
  rbac: ["الأدوار والصلاحيات", "Roles and permissions"],
  reception: ["الاستقبال", "Reception"],
  scheduling: ["الجدولة", "Scheduling"],
  sessions: ["الجلسات", "Sessions"],
  settings: ["الإعدادات", "Settings"],
  tasks: ["المهام", "Tasks"],
  users: ["المستخدمون", "Users"],
};

// Audit actions and patient-timeline event types appear in the same columns.
export const ACTION_LABELS: Labels = { ...TIMELINE_LABELS, ...AUDIT_ACTION_LABELS };
