// Shared presentation labels; event codes remain unchanged in API data.
export const TIMELINE_LABELS: Readonly<Record<string, readonly [string, string]>> = {
  PATIENT_REGISTERED: ["تسجيل المريض", "Patient registered"],
  PATIENT_UPDATED: ["تحديث بيانات المريض", "Patient details updated"],
  CLINICAL_ALERT_CREATED: ["إضافة تنبيه سريري", "Clinical alert added"],
  CLINICAL_ALERT_RESOLVED: ["حل التنبيه السريري", "Clinical alert resolved"],
  CLINICAL_NOTE_ADDED: ["إضافة ملاحظة سريرية", "Clinical note added"],
  DIALYSIS_PLAN_SET: ["تحديث خطة الديلزة", "Dialysis plan updated"],
  PATIENT_MARKED_ABSENT: ["تسجيل غياب المريض", "Patient marked absent"],
  PATIENT_CHECKED_IN: ["تسجيل حضور المريض", "Patient checked in"],
  PATIENT_CHECKED_IN_LATE: ["تسجيل حضور متأخر", "Patient checked in late"],
  EXTRA_SESSION_CREATED: ["إنشاء جلسة إضافية", "Extra session scheduled"],
  EMERGENCY_SESSION_CREATED: ["إنشاء جلسة طارئة", "Emergency session scheduled"],
  MACHINE_ASSIGNED: ["تعيين الجهاز", "Machine assigned"],
  MACHINE_APPROVAL_REQUESTED: ["طلب موافقة على الجهاز", "Machine approval requested"],
  MACHINE_APPROVAL_APPROVED: ["الموافقة على استخدام الجهاز", "Machine use approved"],
  MACHINE_APPROVAL_REJECTED: ["رفض استخدام الجهاز", "Machine use rejected"],
  DIALYSIS_STARTED: ["بدء الديلزة", "Dialysis started"],
  DIALYSIS_COMPLETED: ["اكتمال الديلزة", "Dialysis completed"],
  DIALYSIS_INTERRUPTED: ["توقف الديلزة", "Dialysis interrupted"],
  DIALYSIS_MACHINE_REASSIGNED: ["تغيير جهاز الديلزة", "Dialysis machine reassigned"],
  DIALYSIS_EVENT_NORMAL: ["حدث اعتيادي أثناء الديلزة", "Routine dialysis event"],
  DIALYSIS_EVENT_HYPOTENSION: ["انخفاض ضغط الدم", "Hypotension"],
  DIALYSIS_EVENT_ACCESS_ISSUE: ["مشكلة الوصول الوعائي", "Vascular access issue"],
  DIALYSIS_EVENT_MACHINE_ISSUE: ["مشكلة جهاز الديلزة", "Dialysis machine issue"],
  DIALYSIS_EVENT_MEDICATION_GIVEN: ["إعطاء دواء أثناء الديلزة", "Medication given during dialysis"],
  DIALYSIS_EVENT_PHYSICIAN_CALLED: ["استدعاء الطبيب", "Physician called"],
  DIALYSIS_EVENT_SESSION_INTERRUPTED: ["توقف جلسة الديلزة", "Dialysis session interrupted"],
  DIALYSIS_EVENT_OTHER: ["حدث آخر أثناء الديلزة", "Other dialysis event"],
  DOCTOR_ORDER_MEDICATION: ["أمر دوائي", "Medication order"],
  DOCTOR_ORDER_LAB_REQUEST: ["طلب مختبر من الطبيب", "Doctor’s lab request"],
  DOCTOR_ORDER_NURSING_INSTRUCTION: ["تعليمات تمريضية", "Nursing instructions"],
  DOCTOR_ORDER_DRY_WEIGHT_CHANGE: ["تغيير الوزن الجاف", "Dry weight changed"],
  DOCTOR_ORDER_EXTRA_SESSION_REQUEST: ["طلب جلسة إضافية", "Extra session requested"],
  DOCTOR_ORDER_PHARMACY_RECOMMENDATION: ["توصية للصيدلية", "Pharmacy recommendation"],
  DOCTOR_ORDER_STOPPED: ["إيقاف أمر الطبيب", "Doctor’s order stopped"],
  DOCTOR_ORDER_MODIFIED: ["تعديل أمر الطبيب", "Doctor’s order modified"],
  LAB_ORDER_CREATED: ["إنشاء طلب مختبر", "Lab order created"],
  LAB_RESULT_FINAL: ["اعتماد نتيجة المختبر", "Lab result finalized"],
  LAB_RESULT_AMENDED: ["تصحيح نتيجة المختبر", "Lab result amended"],
  MEDICATION_ADMINISTERED: ["إعطاء الدواء", "Medication administered"],
  MEDICATION_DISPENSED: ["صرف الدواء", "Medication dispensed"],
  SESSION_SUPPLY_OVERRIDE_SET: ["تعديل مستلزمات الجلسة", "Session supplies adjusted"],
  SUPPLY_ISSUED: ["صرف المستلزمات", "Supplies issued"],
  SUPPLY_UNAVAILABLE: ["عدم توفر المستلزمات", "Supplies unavailable"],
  SUPPLY_SUBSTITUTED: ["استبدال المستلزمات", "Supplies substituted"],
  SUPPLY_PROFILE_UPDATED: ["تحديث ملف المستلزمات", "Supply profile updated"],
  INCIDENT_ADVERSE_EVENT: ["حدث ضار", "Adverse event"],
  INCIDENT_INFECTION: ["حادث عدوى", "Infection incident"],
  INCIDENT_VASCULAR_ACCESS_EVENT: ["حادث وصول وعائي", "Vascular access incident"],
  INCIDENT_HOSPITAL_TRANSFER: ["نقل إلى المستشفى", "Hospital transfer"],
  INCIDENT_EMERGENCY_EVENT: ["حادث طارئ", "Emergency incident"],
  INCIDENT_REPEATED_HYPOTENSION: ["انخفاض ضغط متكرر", "Repeated hypotension"],
  INCIDENT_MACHINE_INCIDENT: ["حادث جهاز", "Machine incident"],
};
